import React,{useEffect,useState} from 'react';
import {MapPin,Plus,Loader2,RefreshCw,X} from 'lucide-react';
import {useAuth} from '../../contexts/AuthContext';
type Branch={id:string;ownerUid:string;businessId:string;name:string;type:'headquarters'|'branch'|'warehouse'|'farm_site'|'storefront';address?:string;phone?:string;status:'active'|'inactive'};
export default function BranchesPage(){
 const {currentUser}=useAuth();const[branches,setBranches]=useState<Branch[]>([]),[businessId,setBusinessId]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[showForm,setShowForm]=useState(false),[error,setError]=useState('');
 const[form,setForm]=useState({name:'',type:'branch' as Branch['type'],address:'',phone:''});
 const request=async(path:string,options:RequestInit={})=>{if(!currentUser)throw new Error('Authentication required.');const token=await currentUser.getIdToken(),session=localStorage.getItem('unique_business_session')||'';const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,'X-Business-Session':session,...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||'Business request failed.');return d};
 const load=async()=>{if(!currentUser)return;setLoading(true);setError('');try{const d=await request('/api/business/branches');setBranches(Array.isArray(d.branches)?d.branches:[]);setBusinessId(localStorage.getItem('unique_business_id')||'')}catch(e){setError(e instanceof Error?e.message:'We could not load branches.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[currentUser?.uid]);
 const add=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{await request('/api/business/branches',{method:'POST',body:JSON.stringify(form)});setForm({name:'',type:'branch',address:'',phone:''});setShowForm(false);await load()}catch(e){setError(e instanceof Error?e.message:'We could not create the branch.')}finally{setSaving(false)}};
 const toggle=async(b:Branch)=>{try{await request(`/api/business/branches/${encodeURIComponent(b.id)}`,{method:'PATCH',body:JSON.stringify({status:b.status==='active'?'inactive':'active'})});await load()}catch(e){setError(e instanceof Error?e.message:'We could not update the branch.')}};
 const remove=async(b:Branch)=>{if(!window.confirm('Remove this branch?'))return;try{await request(`/api/business/branches/${encodeURIComponent(b.id)}`,{method:'DELETE'});await load()}catch(e){setError(e instanceof Error?e.message:'We could not remove the branch.')}};
 return <div className="space-y-6 max-w-7xl mx-auto pb-12"><div className="flex flex-col sm:flex-row justify-between sm:items-center gap-4"><div><h1 className="text-2xl font-bold tracking-tight text-slate-900">Branches & Locations</h1><p className="text-sm text-slate-500 mt-1">Manage your storefronts, warehouses, or farm sites.</p></div><div className="flex gap-2"><button onClick={()=>void load()} disabled={loading} className="bg-white border border-slate-200 text-slate-700 px-4 py-2.5 rounded-xl text-sm font-medium flex items-center gap-2"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/> Refresh</button><button onClick={()=>setShowForm(true)} disabled={!businessId} className="bg-slate-900 text-white px-5 py-2.5 rounded-xl text-sm font-medium flex items-center gap-2 disabled:opacity-50"><Plus className="w-4 h-4"/> Add Branch</button></div></div>
 {error&&<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}
 {showForm&&<form onSubmit={add} className="bg-white border border-slate-200 rounded-3xl p-5 space-y-4"><div className="flex items-center justify-between"><h2 className="font-semibold text-slate-900">Add branch or location</h2><button type="button" onClick={()=>setShowForm(false)}><X className="w-5 h-5 text-slate-500"/></button></div><div className="grid sm:grid-cols-2 gap-4"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Location name" className="border border-slate-200 rounded-xl px-4 py-3"/><select value={form.type} onChange={e=>setForm({...form,type:e.target.value as Branch['type']})} className="border border-slate-200 rounded-xl px-4 py-3 bg-white">{['headquarters','branch','warehouse','farm_site','storefront'].map(x=><option key={x} value={x}>{x.replace(/_/g,' ')}</option>)}</select><input value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="Address (optional)" className="border border-slate-200 rounded-xl px-4 py-3"/><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Phone (optional)" className="border border-slate-200 rounded-xl px-4 py-3"/></div><button disabled={saving} className="bg-slate-900 text-white px-5 py-3 rounded-xl font-medium">{saving?'Saving…':'Save Location'}</button></form>}
 {loading?<div className="bg-white border border-slate-200 rounded-3xl p-12 flex justify-center"><Loader2 className="w-7 h-7 animate-spin text-slate-400"/></div>:branches.length===0?<div className="bg-white border border-slate-200 rounded-3xl p-12 text-center"><MapPin className="w-12 h-12 text-slate-400 mx-auto mb-4"/><h3 className="text-lg font-semibold text-slate-900">No branches yet</h3></div>:<div className="bg-white border border-slate-200 rounded-3xl overflow-hidden divide-y divide-slate-100">{branches.map(b=><div key={b.id} className="p-5 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div className="flex items-start gap-3"><MapPin className="w-5 h-5 text-slate-400 mt-1"/><div><h3 className="font-semibold text-slate-900">{b.name}</h3><p className="text-sm text-slate-500 mt-1 capitalize">{b.type.replace(/_/g,' ')}{b.address?` · ${b.address}`:''}</p>{b.phone&&<p className="text-xs text-slate-400 mt-1">{b.phone}</p>}</div></div><div className="flex items-center gap-2"><button onClick={()=>void toggle(b)} className="px-3 py-1 rounded-md text-xs font-bold uppercase bg-slate-100 text-slate-700">{b.status}</button><button onClick={()=>void remove(b)} className="text-xs font-medium text-rose-600 hover:underline">Remove</button></div></div>)}</div>}
 </div>;
}