import React,{useEffect,useState} from 'react';
import {Truck,Plus,Loader2,RefreshCw,X} from 'lucide-react';
import {useAuth} from '../../contexts/AuthContext';
type Supplier={id:string;name:string;companyName:string;phone:string;email?:string;address?:string;category:string;outstandingAmount:number;verificationStatus:string};
export default function SuppliersPage(){
 const{currentUser}=useAuth();const[suppliers,setSuppliers]=useState<Supplier[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[showForm,setShowForm]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');
 const[form,setForm]=useState({name:'',companyName:'',phone:'',email:'',address:'',category:''});
 const request=async(path:string,options:RequestInit={})=>{if(!currentUser)throw new Error('Authentication required.');const token=await currentUser.getIdToken(),session=localStorage.getItem('unique_business_session')||'';const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,'X-Business-Session':session,...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||'Business request failed.');return d};
 const load=async()=>{if(!currentUser)return;setLoading(true);setError('');try{const d=await request('/api/business/suppliers');setSuppliers(Array.isArray(d.suppliers)?d.suppliers:[])}catch(e){setError(e instanceof Error?e.message:'We could not load suppliers.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[currentUser?.uid]);
 const add=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');setSuccess('');try{await request('/api/business/suppliers',{method:'POST',body:JSON.stringify(form)});setForm({name:'',companyName:'',phone:'',email:'',address:'',category:''});setShowForm(false);setSuccess('Supplier added successfully.');await load()}catch(e){setError(e instanceof Error?e.message:'We could not add the supplier.')}finally{setSaving(false)}};
 return <div className="space-y-6 max-w-7xl mx-auto pb-12"><div className="flex flex-col sm:flex-row justify-between sm:items-center gap-4"><div><h1 className="text-2xl font-bold tracking-tight text-slate-900">Suppliers</h1><p className="text-sm text-slate-500 mt-1">Manage vendors, farmers, and distributors.</p></div><button onClick={()=>setShowForm(true)} className="bg-slate-900 text-white px-5 py-2.5 rounded-xl text-sm font-medium flex items-center gap-2"><Plus className="w-4 h-4"/> Add Supplier</button></div>
 {error&&<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}{success&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">{success}</div>}
 {showForm&&<form onSubmit={add} className="bg-white border border-slate-200 rounded-3xl p-5 space-y-4"><div className="flex items-center justify-between"><h2 className="font-semibold text-slate-900">Add supplier</h2><button type="button" onClick={()=>setShowForm(false)}><X className="w-5 h-5 text-slate-500"/></button></div><div className="grid sm:grid-cols-2 gap-4">{[['name','Contact name'],['companyName','Company name'],['phone','Phone number'],['email','Email (optional)'],['category','Supply category'],['address','Address (optional)']].map(([key,placeholder])=><input key={key} type={key==='email'?'email':'text'} required={['name','companyName','phone','category'].includes(key)} value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})} placeholder={placeholder} className="border border-slate-200 rounded-xl px-4 py-3"/>)}</div><button disabled={saving} className="bg-slate-900 text-white px-5 py-3 rounded-xl font-medium">{saving?'Saving…':'Save Supplier'}</button></form>}
 {loading?<div className="bg-white border border-slate-200 rounded-3xl p-12 flex justify-center"><Loader2 className="w-7 h-7 animate-spin text-slate-400"/></div>:suppliers.length===0?<div className="bg-white border border-slate-200 rounded-3xl p-12 text-center"><Truck className="w-12 h-12 text-slate-400 mx-auto mb-4"/><h3 className="text-lg font-semibold text-slate-900">No suppliers yet</h3></div>:<div className="bg-white border border-slate-200 rounded-3xl overflow-hidden"><div className="flex justify-end p-3 border-b border-slate-100"><button onClick={()=>void load()} className="text-sm text-slate-600 flex items-center gap-1"><RefreshCw className="w-4 h-4"/> Refresh</button></div><div className="divide-y divide-slate-100">{suppliers.map(s=><div key={s.id} className="p-5 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div><p className="font-semibold text-slate-900">{s.companyName}</p><p className="text-sm text-slate-500 mt-1">{s.name} · {s.category} · {s.phone}</p></div><span className="px-2.5 py-1 rounded-lg bg-slate-100 text-slate-700 text-xs font-bold uppercase">{s.verificationStatus}</span></div>)}</div></div>}
 </div>;
}