import { FormEvent, useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { FileDown, Send, Sparkles } from "lucide-react";
import { useAuth } from "../contexts/AuthContext";
import { getLanguage, type SupportedLanguage } from "../lib/i18n";

type UniqueAiCapabilities = {
  version: 1;
  readOnly: true;
  contexts: string[];
  mutations: string[];
};

type DiscoveryResult = {
  type: "product" | "service" | "business";
  id: string;
  name: string;
  category?: string;
  description?: string;
  providerName?: string;
  price?: number;
  currency?: string;
  score: number;
};

type AiAccess = {
  mode: "guest" | "registered" | "subscriber";
  limitSeconds: number;
  usedSeconds: number;
  remainingSeconds: number;
};

type ChatMessage = {
  id: string;
  role: "user" | "assistant";
  text: string;
  discovery?: DiscoveryResult[];
};

const shouldLoadDiscovery = (value: string) =>
  /\b(find|search|look for|show me|where can i|where is|available|buy|sell|hire|book|service|product|business|store|marketplace|cement|rice|phone|solar|car|hotel|restaurant|delivery|near me)\b/i.test(value);

function downloadAiPdf(title: string, body: string) {
  const sanitize = (value: string) => value.replace(/₦/g, "NGN ").replace(/[–—]/g, "-").replace(/[‘’]/g, "'").replace(/[“”]/g, '"').replace(/[^\x20-\x7E\n]/g, "");
  const wrap = (value: string, width = 88) => {
    const output: string[] = [];
    for (const raw of sanitize(value).split(/\r?\n/)) {
      if (!raw.trim()) { output.push(""); continue; }
      let line = raw.trim();
      while (line.length > width) {
        let cut = line.lastIndexOf(" ", width);
        if (cut < 20) cut = width;
        output.push(line.slice(0, cut));
        line = line.slice(cut).trimStart();
      }
      output.push(line);
    }
    return output;
  };
  const lines = [sanitize(title).slice(0, 120), "Generated by Unique AI • " + new Date().toLocaleString(), "", ...wrap(body)];
  const pageLines = 48;
  const pages: string[][] = [];
  for (let i = 0; i < lines.length; i += pageLines) pages.push(lines.slice(i, i + pageLines));
  const objects: string[] = ["<< /Type /Catalog /Pages 2 0 R >>", "PAGES_PLACEHOLDER", "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"];
  const pageRefs: number[] = [];
  for (const page of pages) {
    const contentNumber = objects.length + 2;
    const pageNumber = objects.length + 1;
    pageRefs.push(pageNumber);
    const commands = ["BT", "/F1 11 Tf", "50 770 Td", ...page.map((line, index) => {
      const safe = line.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
      return "(" + safe + ") Tj" + (index === page.length - 1 ? "" : " 0 -15 Td");
    }), "ET"].join("\n");
    objects.push("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents " + contentNumber + " 0 R >>");
    objects.push("<< /Length " + commands.length + " >>\nstream\n" + commands + "\nendstream");
  }
  objects[1] = "<< /Type /Pages /Kids [" + pageRefs.map((n) => n + " 0 R").join(" ") + "] /Count " + pageRefs.length + " >>";
  const chunks = ["%PDF-1.4\n%UniqueOne\n"];
  const offsets = [0];
  let length = chunks[0].length;
  objects.forEach((obj, index) => { offsets[index + 1] = length; const chunk = (index + 1) + " 0 obj\n" + obj + "\nendobj\n"; chunks.push(chunk); length += chunk.length; });
  const xrefOffset = length;
  chunks.push("xref\n0 " + (objects.length + 1) + "\n0000000000 65535 f \n");
  for (let i = 1; i <= objects.length; i++) chunks.push(String(offsets[i]).padStart(10, "0") + " 00000 n \n");
  chunks.push("trailer\n<< /Size " + (objects.length + 1) + " /Root 1 0 R >>\nstartxref\n" + xrefOffset + "\n%%EOF");
  const blob = new Blob([chunks.join("")], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = (sanitize(title).replace(/[^A-Za-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 70) || "unique-ai-document") + ".pdf";
  document.body.appendChild(anchor); anchor.click(); anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}
const QUICK_PROMPTS = [
  "What can Unique One do for individuals, families, businesses, and organizations?",
  "How does Unique One bring payments, shopping, services, communication, and discovery together?",
  "How does Unique Store work from discovery to checkout and delivery?",
  "How does UniquePay work for sending and receiving money?",
  "Can my phone number work as my UniquePay account number?",
  "How does UniquePay use a unique person ID for payments?",
  "Can I send money to another Unique One user by email?",
  "What payment, airtime, data, and bill services are planned for UniquePay?",
  "How will bank transfers work inside UniquePay?",
  "How does Unique Store connect with UniquePay?",
  "Can I switch between Unique Store and UniquePay without creating another account?",
  "How can a business register and create its Unique One business presence?",
  "How do business branches and ownership work in Unique One?",
  "How can sellers create and manage products in Unique Store?",
  "How can customers discover products and services near them?",
  "How does Unique Store location work from Nigeria to state, LGA, town, area, landmark, and GPS?",
  "How can I buy, sell, hire, book, send, travel, eat, discover, connect, and grow in Unique Store?",
  "How will business verification work on Unique One?",
  "How can a business manage customers, staff, suppliers, inventory, and orders?",
  "How does Unique One support SMEs and larger organizations?",
  "How can institutions and communities use Unique One?",
  "How can citizens use Unique One services?",
  "How can government services eventually fit into the Unique One ecosystem?",
  "How does Unique One support low-bandwidth users?",
  "Can Unique One work as an installable PWA on Android?",
  "How does Unique One work across web and mobile?",
  "What makes Unique One different from a normal marketplace?",
  "What makes Unique One different from a normal payment app?",
  "How does the Unique One super-app experience work?",
  "What does the human life operating system idea mean in Unique One?",
  "How does the Unique One trust/main branch concept work?",
  "How does Unique AI help me use Unique One?",
  "What can Unique AI access when I am registered?",
  "Can Unique AI understand my businesses, products, orders, and account context?",
  "Can Unique AI change my account, payments, or orders?",
  "Why is Unique AI read-only for protected platform context?",
  "How does Unique AI protect private platform data?",
  "How does Unique AI handle incomplete or missing data?",
  "What happens when Unique AI reaches a context limit?",
  "What happens if Unique AI temporarily fails?",
  "What does a Unique AI request ID do?",
  "How does Unique AI handle an invalid model response?",
  "How does Unique AI prevent another user’s private data from being exposed?",
  "Can Unique AI summarize my current orders?",
  "Can Unique AI summarize my businesses and products?",
  "Can Unique AI explain my inventory information?",
  "Can Unique AI explain my order statuses?",
  "Can Unique AI explain why some platform data may be incomplete?",
  "How can I ask Unique AI about my own platform activity?",
  "What does registered Unique AI context include?",
  "What is available in public Unique AI mode?",
  "How do I register for the full Unique One experience?",
  "How does Unique One authentication protect my account?",
  "How does Unique One handle sessions and access tokens?",
  "How does Unique One protect sensitive actions?",
  "How will transaction PIN protection work?",
  "How will OTP protection work?",
  "How will passkeys work in Unique One?",
  "How can fingerprint or face verification add security?",
  "How does Unique One protect financial routes?",
  "How does Unique One protect Firestore data?",
  "How does Unique One protect product and profile uploads?",
  "How does Unique One protect chat and file uploads?",
  "How are seller and business ownership permissions enforced?",
  "How does Unique One prevent clients from creating fake completed transactions?",
  "How does UniquePay use transaction ledgers and idempotency?",
  "How are Nigerian naira amounts represented safely in UniquePay?",
  "How will UniquePay connect to licensed financial partners?",
  "What role can a banking partner play in UniquePay?",
  "How could NIBSS services fit into UniquePay?",
  "How could NIN and BVN verification fit into UniquePay?",
  "What languages can Unique One support across Africa?",
  "How can Unique One expand from Nigeria to Africa and then globally?",
  "How can Unique One remain affordable as it grows?",
  "How does Unique One handle continuous platform upgrades?",
  "How does Unique Store handle product images?",
  "How can sellers upload product photos?",
  "How can users upload profile photos?",
  "How can users send photos and videos in communication?",
  "How can users send files in Unique One communication?",
  "How will the Unique One communication experience work?",
  "How can chat attachments be previewed before sending?",
  "How can Unique One avoid upload failures and stuck uploads?",
  "How can Unique One provide a WhatsApp-like communication experience?",
  "How can end-to-end encryption fit into Unique One communication?",
  "How does Unique Store handle carts?",
  "How does Unique Store handle checkout?",
  "How does Unique Store handle orders?",
  "How can customers track their orders?",
  "How can sellers manage order status?",
  "How can businesses manage inventory?",
  "How can customers save products or businesses?",
  "How can product hearts and favorites work?",
  "How can businesses showcase their services?",
  "How can providers appear in Discover?",
  "How will Discover use real platform data?",
  "How does the Active Edge experience work?",
  "How can Active Edge surface posts and updates from users and businesses?",
  "How can Unique One combine social updates with discovery?",
  "How can users discover nearby businesses and services?",
  "How can businesses reach relevant customers?",
  "How can customers discover trusted providers?",
  "How will Unique One avoid invented listings and use real platform data?",
  "How can AI help users discover real products and services?",
  "How can Unique One support bookings?",
  "How can Unique One support travel services?",
  "How can Unique One support food discovery and ordering?",
  "How can Unique One support hiring and service requests?",
  "How can Unique One support sending and delivery services?",
  "How can Unique One support business-to-business activity?",
  "How can Unique One support communities and institutions?",
  "How can Unique One support large organizations?",
  "How can Unique One support entrepreneurs starting a business?",
  "How can Unique One help a seller grow?",
  "How can Unique One help a customer save time?",
  "How can Unique One help a business understand its orders?",
  "How can Unique One help businesses understand products and inventory?",
  "How can Unique One connect a business presence to payments?",
  "How can Unique One connect commerce with communication?",
  "How can Unique One connect discovery with transactions?",
  "How can Unique One connect users, businesses, institutions, and communities?",
  "What is the role of the Unique One ID?",
  "How can Unique One identify people and businesses safely?",
  "How can a unique person ID be used instead of a QR code?",
  "How could temporary receiving account numbers work in UniquePay?",
  "How could future UniquePay ATM cards work?",
  "What are UniqueCoins and how might they fit into the future?",
  "How can Unique One support English, French, Hausa, Igbo, and Yoruba?",
  "How does Unique One handle notifications and important updates?",
  "How can Unique One make the home experience personalized?",
  "How can the home page bring together the whole Unique One experience?",
  "How can Unique One keep the interface simple despite many capabilities?",
  "How can Unique One remain fast on slower devices and networks?",
  "How can Unique One provide a consistent experience across Android and desktop?",
  "How can I find my account, business, orders, and products quickly?",
  "How can I use Unique AI to learn a feature step by step?",
  "Ask Unique AI to explain Unique Store.",
  "Ask Unique AI to explain UniquePay.",
  "Ask Unique AI to explain Unique One security.",
  "Ask Unique AI to explain my business dashboard.",
  "Ask Unique AI to explain my orders.",
  "Ask Unique AI to explain my products.",
  "Ask Unique AI to explain my account.",
  "What is Unique One building next?",
  "What capabilities are already available in Unique One?",
  "Which Unique One features are connected today?",
  "How can I get help when a Unique One feature fails?",
  "What should I give support when Unique One reports an error?",
  "What does a support request ID mean?",
  "What does it mean when Unique One says data is incomplete?",
  "How does Unique One handle service failures safely?",
  "How does Unique One keep protected actions separate from AI answers?",
  "What information should never be shared in a support request?",
];

export default function UniqueAiPage() {
  const { currentUser } = useAuth();
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [lastFailedMessage, setLastFailedMessage] = useState<string | null>(null);
  const [requestState, setRequestState] = useState<"idle" | "sending" | "retrying">("idle");
  const [lastRequestId, setLastRequestId] = useState<string | null>(null);
  const [suggestedIndex, setSuggestedIndex] = useState(0);
  const [language, setLanguage] = useState<SupportedLanguage>(getLanguage());
  const [aiAccess, setAiAccess] = useState<AiAccess | null>(null);
  const [displayRemainingSeconds, setDisplayRemainingSeconds] = useState<number | null>(null);
  const [premiumNoticeOpen, setPremiumNoticeOpen] = useState(false);
  const guestSessionIdRef = useRef<string | null>(null);

  useEffect(() => {
    const handleLanguageChange = (event: Event) => {
      setLanguage((event as CustomEvent<SupportedLanguage>).detail);
    };
    window.addEventListener("unique-language-change", handleLanguageChange);
    return () => window.removeEventListener("unique-language-change", handleLanguageChange);
  }, []);
  const messagesEndRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (currentUser || guestSessionIdRef.current) return;
    const storageKey = "unique-ai-guest-session-v1";
    let sessionId = window.sessionStorage.getItem(storageKey);
    if (!sessionId) {
      sessionId = crypto.randomUUID().replace(/-/g, "");
      window.sessionStorage.setItem(storageKey, sessionId);
    }
    guestSessionIdRef.current = sessionId;
  }, [currentUser]);

  useEffect(() => {
    if (displayRemainingSeconds === null || displayRemainingSeconds <= 0) return;
    const intervalId = window.setInterval(() => {
      setDisplayRemainingSeconds((value) => value === null ? null : Math.max(0, value - 1));
    }, 1000);
    return () => window.clearInterval(intervalId);
  }, [displayRemainingSeconds]);

  const formatAiTime = (seconds: number) => {
    const safe = Math.max(0, Math.floor(seconds));
    const hours = Math.floor(safe / 3600);
    const minutes = Math.floor((safe % 3600) / 60);
    const secs = safe % 60;
    if (hours > 0) return `${hours}h ${minutes}m`;
    return `${minutes}m ${secs.toString().padStart(2, "0")}s`;
  };

  useEffect(() => {
    if (aiAccess?.mode === "subscriber") return;
    const noticeKey = "unique-ai-premium-notice-v1";
    if (window.sessionStorage.getItem(noticeKey)) return;
    const timeoutId = window.setTimeout(() => {
      window.sessionStorage.setItem(noticeKey, "1");
      setPremiumNoticeOpen(true);
      window.setTimeout(() => setPremiumNoticeOpen(false), 8500);
    }, 25_000);
    return () => window.clearTimeout(timeoutId);
  }, [aiAccess?.mode]);

  useEffect(() => {
    const intervalId = window.setInterval(() => {
      setSuggestedIndex((current) => (current + 1) % QUICK_PROMPTS.length);
    }, 6_000);
    return () => window.clearInterval(intervalId);
  }, []);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth", block: "end" });
  }, [messages, loading, error]);

  const sendMessage = async (event?: FormEvent, retryMessage?: string) => {
    event?.preventDefault();
    const trimmed = (retryMessage ?? message).trim();
    if (!trimmed || loading) return;

    setError("");
    setLastFailedMessage(null);
    setMessage("");
    if (!retryMessage) {
      const userMessage: ChatMessage = {
        id: crypto.randomUUID(),
        role: "user",
        text: trimmed,
      };
      setMessages((current) => [...current, userMessage]);
    }
    setLoading(true);
    setRequestState(retryMessage ? "retrying" : "sending");
    const controller = new AbortController();
    const timeoutId = window.setTimeout(() => controller.abort(), 30_000);

    try {
      const requestId = crypto.randomUUID();
      const history = messages.slice(-6).map(({ role, text }) => ({ role, text }));
      const headers: Record<string, string> = {
        "Content-Type": "application/json",
        "X-Request-ID": requestId,
      };
      if (currentUser) {
        headers.Authorization = `Bearer ${await currentUser.getIdToken()}`;
      } else if (guestSessionIdRef.current) {
        headers["X-AI-Session-ID"] = guestSessionIdRef.current;
      }
      const response = await fetch(currentUser ? "/api/ai/chat" : "/api/ai/public-chat", {
        method: "POST",
        headers,
        body: JSON.stringify({ message: trimmed, history, preferredLanguage: language }),
        signal: controller.signal,
      });

      const payload = (await response.json().catch(() => null)) as
        | { message?: string; readOnly?: boolean; requestId?: string; capabilities?: UniqueAiCapabilities; error?: { message?: string; code?: string }; aiAccess?: AiAccess }
        | null;
      if (payload?.aiAccess) {
        setAiAccess(payload.aiAccess);
        setDisplayRemainingSeconds(payload.aiAccess.remainingSeconds);
      }
      const remainingHeader = response.headers.get("X-AI-Remaining-Seconds");
      if (remainingHeader && /^\\d+$/.test(remainingHeader)) {
        setDisplayRemainingSeconds(Number(remainingHeader));
      }

      const responseRequestId = response.headers.get("X-Request-ID")?.trim();
      if (responseRequestId && !/^[A-Za-z0-9._:-]{1,64}$/.test(responseRequestId)) {
        throw new Error("Unique AI returned an invalid response request ID.");
      }
      if (!response.ok) {
        const errorRequestId =
          responseRequestId ||
          (typeof payload?.requestId === "string" ? payload.requestId : undefined);
        if (errorRequestId) setLastRequestId(errorRequestId);
        throw new Error(payload?.error?.message || "Unique AI is temporarily unavailable.");
      }

      if (payload?.readOnly !== true) {
        throw new Error("Unique AI returned an invalid response contract.");
      }
      if (currentUser) {
        if (
          !payload.capabilities ||
          payload.capabilities.version !== 1 ||
          payload.capabilities.readOnly !== true ||
          !Array.isArray(payload.capabilities.contexts) ||
          JSON.stringify([...payload.capabilities.contexts].sort()) !== JSON.stringify(["account", "businesses", "orders", "products"]) ||
          !Array.isArray(payload.capabilities.mutations) ||
          payload.capabilities.mutations.length !== 0
        ) {
          throw new Error("Unique AI returned an invalid capability contract.");
        }
      }

      if (payload.requestId !== undefined && payload.requestId !== requestId) {
        throw new Error("Unique AI returned a mismatched request ID.");
      }

      if (typeof payload?.requestId !== "string" || !/^[A-Za-z0-9._:-]{1,64}$/.test(payload.requestId)) {
        throw new Error("Unique AI returned an invalid request ID.");
      }

      if (typeof payload?.message !== "string" || !payload.message.trim()) {
        throw new Error("Unique AI returned an empty response.");
      }

      setLastRequestId(responseRequestId || payload.requestId);

      let discoveryResults: DiscoveryResult[] = [];
      if (shouldLoadDiscovery(trimmed)) {
        try {
          const discoveryResponse = await fetch("/api/ai/discovery", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ message: trimmed }),
            signal: controller.signal,
          });
          if (discoveryResponse.ok) {
            const discoveryPayload = (await discoveryResponse.json().catch(() => null)) as { results?: DiscoveryResult[] } | null;
            if (Array.isArray(discoveryPayload?.results)) {
              discoveryResults = discoveryPayload.results
                .filter((item) => item && typeof item.id === "string" && typeof item.name === "string")
                .slice(0, 6);
            }
          }
        } catch {
          // AI text remains usable when the optional discovery cards are unavailable.
        }
      }

      setMessages((current) => [
        ...current,
        { id: crypto.randomUUID(), role: "assistant", text: payload.message!.trim(), ...(discoveryResults.length ? { discovery: discoveryResults } : {}) },
      ]);
    } catch (err) {
      setLastFailedMessage(trimmed);
      if (err instanceof DOMException && err.name === "AbortError") {
        setError("Unique AI took too long to respond. Please try again.");
      } else {
        setError(err instanceof Error ? err.message : "Unable to contact Unique AI.");
      }
    } finally {
      window.clearTimeout(timeoutId);
      setLoading(false);
      setRequestState("idle");
    }
  };

  return (
    <>
      <style>{`
        @keyframes uniqueAiSuggestedSlide {
          0% { opacity: 0; transform: translate3d(28px, 0, 0); filter: blur(3px); }
          65% { opacity: 1; transform: translate3d(-2px, 0, 0); filter: blur(0); }
          100% { opacity: 1; transform: translate3d(0, 0, 0); filter: blur(0); }
        }
        @keyframes uniqueAiSuggestionSweep {
          0% { transform: translateX(-105%); opacity: .15; }
          12% { opacity: 1; }
          88% { opacity: 1; }
          100% { transform: translateX(105%); opacity: .15; }
        }
        @keyframes uniqueAiSuggestionGlow {
          0%, 100% { opacity: .35; }
          50% { opacity: .95; }
        }
        @keyframes uniqueAiTypingDot {
          0%, 60%, 100% { transform: translateY(0) scale(.72); opacity: .35; }
          30% { transform: translateY(-4px) scale(1); opacity: 1; }
        }
        @keyframes uniqueAiTypingGlow {
          0%, 100% { opacity: .35; transform: scale(.92); }
          50% { opacity: .9; transform: scale(1.08); }
        }
        @keyframes uniqueAiComposerShine {
          0% { transform: translateX(-120%); opacity: 0; }
          25% { opacity: .45; }
          70% { opacity: .2; }
          100% { transform: translateX(120%); opacity: 0; }
        }
        @keyframes uniqueAiSearchGlow {
          0%, 100% { opacity: .42; transform: scale(.985); }
          50% { opacity: .88; transform: scale(1.012); }
        }
        @keyframes uniqueAiSearchSmoke {
          0%, 100% { transform: translate3d(-2%, 0, 0) scale(1); opacity: .28; }
          50% { transform: translate3d(2%, -1px, 0) scale(1.035); opacity: .55; }
        }
        @keyframes uniqueAiTitleFloat {
          0%, 100% { transform: translate3d(0, 0, 0); text-shadow: 0 0 0 rgba(16,185,129,0); }
          50% { transform: translate3d(0, -3px, 0); text-shadow: 0 0 18px rgba(16,185,129,.24); }
        }
        @keyframes uniqueAiOrbPulse {
          0%, 100% { transform: scale(.98); }
          50% { transform: scale(1.06); }
        }
        @keyframes uniqueAiOrbSweep {
          0% { transform: rotate(0deg); }
          100% { transform: rotate(360deg); }
        }
        @keyframes uniqueAiFlagOrbit {
          0% { transform: rotate(0deg) translateX(25px) rotate(0deg); }
          25% { transform: rotate(90deg) translateX(25px) rotate(-90deg); }
          50% { transform: rotate(180deg) translateX(25px) rotate(-180deg); }
          75% { transform: rotate(270deg) translateX(25px) rotate(-270deg); }
          100% { transform: rotate(360deg) translateX(25px) rotate(-360deg); }
        }
      `}</style>
      <div className="flex h-full min-h-0 min-w-0 flex-col gap-2 overflow-x-hidden sm:gap-4">
      {aiAccess && (
        <div className="flex items-center justify-between gap-3 rounded-xl border border-emerald-100 bg-emerald-50/80 px-3 py-2 text-xs text-emerald-900 shadow-sm">
          <div className="min-w-0">
            <div className="font-semibold">
              {aiAccess.mode === "guest" ? "Guest AI access" : aiAccess.mode === "registered" ? "Daily AI access" : "Unique AI Premium"}
            </div>
            <div className="truncate opacity-80">
              {aiAccess.mode === "guest"
                ? "Register to unlock 1 hour of Unique AI every day."
                : aiAccess.mode === "registered"
                  ? "Your daily allowance is shared across conversations."
                  : "Extended AI access with fair-use protection."}
            </div>
          </div>
          <div className="flex shrink-0 items-center gap-2">
            {aiAccess.mode !== "subscriber" && (
              <Link
                to="/ai/premium"
                className="rounded-full border border-emerald-300 bg-white px-2.5 py-1.5 text-[10px] font-bold text-emerald-700 shadow-sm transition hover:bg-emerald-50"
              >
                ✨ Premium
              </Link>
            )}
            <div className="text-right">
              <div className="font-bold">{displayRemainingSeconds === null ? formatAiTime(aiAccess.remainingSeconds) : formatAiTime(displayRemainingSeconds)}</div>
              <div className="opacity-70">remaining</div>
            </div>
          </div>
        </div>
      )}
      {premiumNoticeOpen && aiAccess?.mode !== "subscriber" && (
        <div className="pointer-events-none fixed inset-x-3 top-20 z-40 flex justify-center sm:inset-x-auto sm:right-5 sm:top-24 sm:w-[360px]">
          <div className="pointer-events-auto w-full rounded-2xl border border-emerald-200 bg-white/95 p-3 shadow-[0_14px_45px_rgba(15,23,42,.16)] backdrop-blur-xl">
            <div className="flex items-start gap-3">
              <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-slate-950 text-sm text-emerald-300 shadow-[0_0_16px_rgba(16,185,129,.28)]">✨</div>
              <div className="min-w-0 flex-1">
                <div className="text-xs font-black text-slate-900">Unique AI Premium</div>
                <div className="mt-0.5 text-[11px] leading-4 text-slate-500">Extended AI access from ₦180. Your conversation stays exactly where it is.</div>
                <Link to="/ai/premium" className="mt-2 inline-flex rounded-full bg-slate-950 px-3 py-1.5 text-[10px] font-bold text-white hover:bg-emerald-600">View plans</Link>
              </div>
              <button type="button" onClick={() => setPremiumNoticeOpen(false)} className="shrink-0 px-1 text-slate-400 hover:text-slate-700" aria-label="Dismiss Premium notice">×</button>
            </div>
          </div>
        </div>
      )}
      <div className="flex items-center justify-between gap-2 px-1">
        <div className="flex min-w-0 items-center gap-1.5">
          <Sparkles className="h-3.5 w-3.5 shrink-0 text-emerald-500" aria-hidden="true" />
          <span className="text-[10px] font-bold uppercase tracking-[0.12em] text-slate-500">Try asking</span>
          <span className="hidden text-[10px] text-slate-400 sm:inline">— a quick idea to get started</span>
        </div>
        {aiAccess?.mode !== "subscriber" && (
          <Link to="/ai/premium" className="shrink-0 text-[10px] font-bold text-emerald-700 hover:text-emerald-800">Premium plans →</Link>
        )}
      </div>
      <div className="relative min-w-0 overflow-hidden rounded-2xl border border-emerald-100/90 bg-gradient-to-r from-white via-emerald-50/70 to-white p-2.5 shadow-[0_4px_18px_rgba(15,23,42,.045)] sm:p-3">
        <div className="pointer-events-none absolute inset-y-0 left-0 w-1 rounded-l-2xl bg-gradient-to-b from-emerald-300 via-emerald-500 to-teal-300" aria-hidden="true" />
        <div className="pointer-events-none absolute -right-5 -top-7 h-20 w-20 rounded-full bg-emerald-300/15 blur-2xl" style={{ animation: "uniqueAiSuggestionGlow 2.8s ease-in-out infinite" }} aria-hidden="true" />
        <button
          key={QUICK_PROMPTS[suggestedIndex]}
          type="button"
          disabled={loading}
          onClick={() => setMessage(QUICK_PROMPTS[suggestedIndex])}
          className="group relative flex w-full min-w-0 items-center gap-2.5 rounded-xl px-1.5 py-1 text-left transition-colors hover:bg-white/80 disabled:opacity-60 sm:gap-3 sm:px-2"
          aria-label={`Use suggested question: ${QUICK_PROMPTS[suggestedIndex]}`}
        >
          <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl border border-emerald-100 bg-white text-emerald-600 shadow-sm sm:h-9 sm:w-9">
            <Sparkles className="h-4 w-4" aria-hidden="true" />
          </span>
          <span className="min-w-0 flex-1">
            <span className="mb-0.5 block text-[9px] font-bold uppercase tracking-[0.1em] text-emerald-700/80">Suggested prompt</span>
            <span
              className="block min-w-0 whitespace-normal break-words text-[13px] font-semibold leading-[1.4rem] text-slate-800 transition-colors group-hover:text-emerald-800 sm:text-sm"
              style={{ animation: "uniqueAiSuggestedSlide 900ms cubic-bezier(.22,1,.36,1) both" }}
            >
              {QUICK_PROMPTS[suggestedIndex]}
            </span>
          </span>
          <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-emerald-100 bg-white text-sm font-bold text-emerald-700 transition-transform group-hover:translate-x-0.5" aria-hidden="true">↗</span>
        </button>
        <div className="pointer-events-none absolute inset-x-2 bottom-0.5 h-px overflow-hidden bg-emerald-100" aria-hidden="true">
          <span key={suggestedIndex} className="absolute inset-y-0 left-0 w-1/2 rounded-full bg-emerald-400/80" style={{ animation: "uniqueAiSuggestionSweep 5.5s linear both" }} />
        </div>
      </div>

      <div className="flex min-h-0 flex-1 flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <div className="min-w-0 flex-1 overflow-y-auto overscroll-contain p-2.5 sm:p-6">
          {messages.length === 0 ? (
            <div className="mx-auto flex h-full max-w-2xl flex-col items-center justify-end pb-2 text-center sm:pb-4">
              <div className="unique-ai-platform-mark relative flex h-[58px] w-[58px] translate-y-0 items-center justify-center sm:h-16 sm:w-16" aria-hidden="true">
                <span className="absolute -inset-3 rounded-full bg-emerald-300/20 blur-2xl" style={{ animation: "uniqueAiSearchGlow 3.6s ease-in-out infinite" }} />
                <span className="absolute -inset-1.5 rounded-full border border-emerald-300/30" style={{ animation: "uniqueAiOrbPulse 3s ease-in-out infinite" }} />
                <span className="absolute inset-[-8px] rounded-full border border-emerald-400/20" style={{ animation: "uniqueAiOrbSweep 5.5s linear infinite" }} />
                <span className="absolute inset-[-12px] flex items-center justify-center" style={{ animation: "uniqueAiFlagOrbit 6s linear infinite" }}>
                  <span className="flex h-5 w-7 items-center justify-center overflow-hidden rounded-[4px] border border-white/70 bg-white text-[14px] leading-none shadow-[0_2px_8px_rgba(15,23,42,.22)]">🇳🇬</span>
                </span>
                <span className="absolute inset-[-5px] rounded-full border border-emerald-200/20 bg-emerald-400/10 blur-md" style={{ animation: "uniqueAiOrbPulse 2.6s ease-in-out infinite" }} />
                <span className="relative z-10 flex h-12 w-12 items-center justify-center rounded-full border border-white/90 bg-slate-950 text-[11px] font-black tracking-[0.12em] text-emerald-300 shadow-[0_0_22px_rgba(16,185,129,.38)] sm:h-14 sm:w-14 sm:text-xs">
                  <span className="relative">AI<span className="absolute -right-1 -top-1 h-1 w-1 rounded-full bg-white shadow-[0_0_5px_rgba(255,255,255,.9)]" /></span>
                </span>
              </div>
            </div>
          ) : (
            <div className="mx-auto max-w-3xl space-y-4">
              {messages.map((item) => (
                <div
                  key={item.id}
                  className={`flex ${item.role === "user" ? "justify-end" : "justify-start"}`}
                >
                  <div
                    className={`relative max-w-[88%] whitespace-pre-wrap rounded-[22px] px-4 py-3 text-sm leading-6 ${item.role === "user" ? "rounded-br-md bg-slate-900 text-white shadow-slate-900/10" : "rounded-bl-md border border-slate-200/80 bg-white text-slate-800 shadow-black/5"}`}
                  >
                    {item.role === "assistant" && (
                      <div className="mb-1.5 flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-[0.14em] text-emerald-600">
                        <span className="unique-ai-mini-mark relative flex h-4 w-4 items-center justify-center rounded-full bg-emerald-500 text-[6px] font-black text-white shadow-[0_0_10px_rgba(52,211,153,.45)]">
                          UP
                          <span className="absolute inset-0 rounded-full border border-emerald-200/60" />
                        </span>
                        Unique AI
                      </div>
                    )}
                    <div>{item.text}</div>
                    {item.role === "assistant" && (
                      <button type="button" onClick={() => downloadAiPdf("Unique AI Document", item.text)} className="mt-3 inline-flex items-center gap-1.5 rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1.5 text-[11px] font-bold text-emerald-700 transition hover:border-emerald-300 hover:bg-emerald-100" aria-label="Generate PDF from this Unique AI response">
                        <FileDown className="h-3.5 w-3.5" />
                        Generate PDF
                      </button>
                    )}
                    {item.discovery && item.discovery.length > 0 && (
                      <div className="mt-3 space-y-2 border-t border-slate-200/80 pt-3">
                        <div className="text-[10px] font-bold uppercase tracking-[0.14em] text-emerald-600">Live Unique One results</div>
                        <div className="grid gap-2 sm:grid-cols-2">
                          {item.discovery.map((result) => (
                            <Link
                              key={`${result.type}-${result.id}`}
                              to={result.type === "product" ? `/store/search?q=${encodeURIComponent(result.name)}` : `/store/search?q=${encodeURIComponent(result.name)}`}
                              className="block rounded-xl border border-slate-200 bg-slate-50/80 p-2.5 text-left transition hover:border-emerald-300 hover:bg-emerald-50/50"
                            >
                              <div className="flex items-center justify-between gap-2">
                                <span className="text-[9px] font-bold uppercase tracking-[0.12em] text-slate-400">{result.type}</span>
                                {typeof result.price === "number" && (
                                  <span className="text-[10px] font-bold text-emerald-700">{result.currency || "NGN"} {result.price.toLocaleString()}</span>
                                )}
                              </div>
                              <div className="mt-1 text-xs font-semibold leading-4 text-slate-800">{result.name}</div>
                              {(result.category || result.providerName) && (
                                <div className="mt-1 truncate text-[10px] text-slate-500">{result.providerName || result.category}</div>
                              )}
                            </Link>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              ))}
              <div ref={messagesEndRef} aria-hidden="true" />
              {loading && (
                <div className="flex justify-start">
                  <div className="relative flex items-center gap-3 rounded-[22px] rounded-bl-md border border-emerald-100 bg-white px-4 py-3 shadow-sm">
                    <span className="absolute -left-2 top-1/2 h-8 w-8 -translate-y-1/2 rounded-full bg-emerald-300/25 blur-xl" style={{ animation: "uniqueAiTypingGlow 1.8s ease-in-out infinite" }} aria-hidden="true" />
                    <span className="relative flex h-7 w-7 items-center justify-center rounded-full bg-slate-950 text-[8px] font-black text-emerald-300 shadow-[0_0_14px_rgba(52,211,153,.35)]">U1</span>
                    <span className="flex items-center gap-1" aria-label={requestState === "retrying" ? "Retrying Unique AI" : "Unique AI is typing"}>
                      {[0, 1, 2].map((delay) => (
                        <span key={delay} className="h-1.5 w-1.5 rounded-full bg-emerald-500" style={{ animation: `uniqueAiTypingDot 1.1s ease-in-out ${delay * 140}ms infinite` }} />
                      ))}
                    </span>
                    <span className="text-xs font-medium text-slate-500">{requestState === "retrying" ? "Retrying…" : "Typing…"}</span>
                  </div>
                </div>
              )}
            </div>
          )}
        </div>

        {error && (
          <div className="flex items-center justify-between gap-3 border-t border-red-100 bg-red-50 px-4 py-3 text-sm text-red-700">
            <span role="alert">{error}</span>
            {lastFailedMessage && !loading && (
              <button
                type="button"
                onClick={() => {
                  void sendMessage(undefined, lastFailedMessage);
                }}
                className="shrink-0 rounded-lg border border-red-200 bg-white px-3 py-1.5 font-medium text-red-700 hover:bg-red-100"
              >
                Retry
              </button>
            )}
          </div>
        )}

        <form onSubmit={sendMessage} className="shrink-0 border-t border-slate-200/80 bg-white/95 px-2.5 pb-2.5 pt-2 backdrop-blur-xl sm:px-4 sm:pb-4 sm:pt-3">
          <div className="unique-ai-search-shell relative mx-auto flex max-w-3xl items-end gap-2 overflow-visible rounded-[26px]">
            <span className="pointer-events-none absolute -inset-1 rounded-[30px] bg-emerald-300/20 blur-md" aria-hidden="true" />
            <span className="pointer-events-none absolute -inset-[2px] rounded-[28px] border border-emerald-300/40 bg-gradient-to-r from-emerald-300/10 via-white/30 to-teal-300/10 blur-[1px]" style={{ animation: "uniqueAiSearchGlow 3.8s ease-in-out infinite" }} aria-hidden="true" />
            <span className="pointer-events-none absolute -inset-2 rounded-[32px] bg-[radial-gradient(ellipse_at_center,rgba(16,185,129,0.20),transparent_68%)] blur-lg" style={{ animation: "uniqueAiSearchSmoke 5s ease-in-out infinite" }} aria-hidden="true" />
            <div className="relative flex min-w-0 flex-1 items-end gap-2 overflow-hidden rounded-[26px] border border-emerald-200/80 bg-white/95 p-1.5 shadow-[0_0_22px_rgba(16,185,129,0.2)] backdrop-blur-xl transition-all duration-300 focus-within:border-emerald-400 focus-within:bg-white focus-within:shadow-[0_0_34px_rgba(16,185,129,0.34)]">
              <span className="pointer-events-none absolute inset-y-0 left-0 w-1/3 -translate-x-full bg-gradient-to-r from-transparent via-emerald-200/35 to-transparent" style={{ animation: "uniqueAiComposerShine 3.8s ease-in-out infinite" }} aria-hidden="true" />
              <span className="pointer-events-none absolute inset-x-10 top-0 h-px bg-gradient-to-r from-transparent via-emerald-300/80 to-transparent" style={{ animation: "uniqueAiComposerShine 2.8s ease-in-out infinite" }} aria-hidden="true" />
              <textarea
                value={message}
                onChange={(event) => setMessage(event.target.value)}
                onKeyDown={(event) => {
                  if (event.key === "Enter" && !event.shiftKey) {
                    event.preventDefault();
                    void sendMessage();
                  }
                }}
                rows={1}
                maxLength={4000}
                disabled={loading}
                aria-label="Message Unique AI"
                placeholder="Ask Unique AI anything,"
                className="relative min-h-[42px] min-w-0 flex-1 resize-none bg-transparent px-3 py-2.5 text-sm leading-5 text-slate-800 outline-none placeholder:text-slate-400 disabled:opacity-60 sm:min-h-[44px] sm:px-4 sm:py-3"
              />
              <button type="submit" disabled={!message.trim() || loading} aria-label="Send message" className="relative inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-slate-950 text-white shadow-[0_4px_14px_rgba(15,23,42,.2)] transition-all duration-200 hover:-translate-y-0.5 hover:bg-emerald-600 hover:shadow-[0_6px_18px_rgba(16,185,129,.25)] disabled:translate-y-0 disabled:cursor-not-allowed disabled:bg-slate-300 disabled:shadow-none sm:h-11 sm:w-11">
                <Send className="h-4 w-4" />
              </button>
            </div>
          </div>
          {!currentUser && (
            <div className="mt-2 flex items-center justify-between gap-2 rounded-xl border border-emerald-100 bg-emerald-50 px-2.5 py-2 text-[10px] leading-4 text-emerald-800 sm:mt-3 sm:gap-3 sm:px-3 sm:text-xs">
              <span className="min-w-0 line-clamp-2">Enjoying Unique AI? Register to unlock your full Unique One experience and personalized AI.</span>
              <Link to="/register" className="shrink-0 rounded-full bg-slate-900 px-2.5 py-1.5 font-bold text-white sm:px-3">Register free</Link>
            </div>
          )}
          <div className="mt-1.5 flex min-w-0 items-center justify-between gap-2 px-0.5 text-[9px] leading-3.5 text-slate-400 sm:mt-2 sm:gap-3 sm:text-xs sm:leading-4">
            <span className="min-w-0 truncate">{currentUser ? "Registered mode: authorized Unique One context; mutations remain protected." : "Public mode is free. Register for personalized Unique One context."}</span>
            <span className="max-w-full truncate text-left sm:text-right" aria-live="polite">
              {lastRequestId ? `Request: ${lastRequestId}` : "Support request ID will appear after a response"} · {message.length}/4000
            </span>
          </div>
        </form>
      </div>
    </div>
    </>
  );
}